### ISSUE TITLE
Make cleanup interval configurable

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.DataBus.AzureBlobStorage#12]
If there is a large TTL configured the databus should not query frequently

**Comment by wettsten** [comment]
could you make the query frequency configurable? maybe even turn it off if we had our own method of cleanup?

**Comment by SeanFeldman** [comment]
@wettsten I'd think that if you set cleanup interval to 0, it would be considered as disabled.

**Comment by wettsten** [comment]
@SeanFeldman yep, that makes sense.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/commit/eaadda9ae0ce8b1cf711149fd85a772c44b44eea
