### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.DataBus.AzureBlobStorage#19]
PoA:
- [x] Bump up dependencies
- [x] mark PRs/issues with the milestone
- [x] create `release-1.1`
- [x] release RC to myget
- [x] smoke test 
- [ ] merge to master and release to myget
- [ ] bump up docs
- [x] release in cohort with other Azure libs
- [x] announce

For cohort release see https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/187

**Comment by SeanFeldman** [comment]
Released
