### ISSUE TITLE
Use containers to make removal of expired items more efficient

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.DataBus.AzureBlobStorage#2]
Connects to https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/issues/14

Right now we have to go through all the databus items to find the ones that are expired. Instead we should store the expired ones in 1 our more separate containers to make the deletion more efficient. Eg one per hour.

**Comment by danielmarbach** [comment]
Closing, reason see https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/issues/14#issuecomment-343955495
