### ISSUE TITLE
Retire support branch that is no longer needed

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.DataBus.AzureBlobStorage#27]
According to our [support policy](https://docs.particular.net/nservicebus/upgrades/supported-versions#databus-packages-nservicebus-databus-azureblobstorage), support branch `support-1.0` is out of support.

Do we need to remove this branch?

**Comment by SimonCropp** [comment]
Consider a client who has a critical case and says "i can update to 1.1". If the support response is "you are out of luck and we wont help u until u update" then i think u can remove the branch.

**Comment by SeanFeldman** [comment]
This was a question, not an instruction @SimonCropp.

Playing devil's advocate - why do we then advertise what versions are supported and have support policy in place?

**Comment by SimonCropp** [comment]
just to be clear i am happy to remove the branch. i just wanted to make the ramifications clear

>  why do we then advertise what versions are supported and have support policy in place

IMO i think we spend too much time on supporting unsupported versions.

**Comment by Scooletz** [comment]
This can be addressed by a tag, can't it @SimonCropp Just go to the recent covering the specific version.

**Comment by SimonCropp** [comment]
@Scooletz yeah we discussed that as a backup option in slack

**Comment by SeanFeldman** [comment]
Tag and commit (while not the most convenient, still can serve the purpose if needed).

**Comment by SimonCropp** [comment]
One thing I thought of. Given some support branch may never be merged back, the commit with the given tag may only exist on that branch. If u remove the branch, can u still recover the tag

**Comment by SeanFeldman** [comment]
> support branch may never be merged back

@SimonCropp why would it be? Support branches are intended to exist on their own.

**Comment by SimonCropp** [comment]
yes sorry. Support branches are intended to exist on their. so if u delete one cane u recover it from the tag?

**Comment by SeanFeldman** [comment]
​See no reason why not. Would create a branch from the tag commit and
that's it.
