### ISSUE TITLE
Databus Cleanup - Very Costly

### ISSUE THREAD

**Issue by jpalac** [Particular/NServiceBus.DataBus.AzureBlobStorage#53]
## Who's affected

Anyone using Azure DataBus with the  built-in mechanism to perform Storage blobs cleanup enabled.

## Symptoms

High Azure Storage bill mostly attributed to the `GetBlobProperties()` API call.

## Original issue 

When we moved from SQL Server to Azure transport, we started using databus (AzureDataBus) for large messages, and our monthly Azure bill went up by around 5K. After looking into it, we figured out that it was the blob cleanup process causing the cost increase. We then turned the cleanup off (dataBus.CleanupInterval(0)) and the bill went back to normal.

Apart from having a look as to why the cleanup process is so costly and seeing if it can be optomised, I'd like to suggest to have the process off by default to avoid these "surprise" costs.

We are running all endpoints in the same region, and we have about 18 endpoints running that use the databus, although not all messages sent are large. I'd say 30-40% of the messages would have a blob.

**Comment by SeanFeldman** [comment]
Thank you @jpalac for raising the issue.

The default time for cleanup interval is set to [5 minutes](https://docs.particular.net/nservicebus/messaging/databus/azure-blob-storage). With 18 endpoints, each endpoint will perform a cleanup. And if endpoints are scaled, each instance will do that.

We'll review this issue, but until then, there are a few options you could follow:

1. Disable cleanup altogether. This will still require some sort of cleanup on your end.
1. Manually control what endpoints would perform cleanup. This will reduce number of requests to the Storage account. 
1. Use Azure Functions to perform Azure Blob Storage DataBus cleanup. We have a [sample](https://docs.particular.net/samples/azure/blob-storage-databus-cleanup-function/) to show how to set it up.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/commit/4a5a65f69c1119e004c1b0f837f78c33547d1c24
