### ISSUE TITLE
DataBus limits all outgoing HTTP connections to 1

### ISSUE THREAD

**Issue by marcelvwe** [Particular/NServiceBus.DataBus.AzureBlobStorage#59]
### Symptoms

Azure DataBus limits all outgoing HTTP connections to 1.

### Who's affected

Anyone using Azure DataBus.

### Root cause

The current Azure Blob Storage DataBus implementation adjusts the global `DefaultConnectionLimit` of the `ServicePointManager` to the value of the DataBus setting `NumberOfIOThreads` (default = 1).

This causes all other HTTP requests made by the application to be limited to the same NumberOfIOThreads setting, if no `ServicePoint` object has been created before adjusting the global setting.

In fact, I even doubt if changing this setting for the DataBus is necessary, since it is already covered with the BlobStorage specific `ServiceClient.DefaultRequestOptions.ParallelOperationThreadCount` setting. In fact, Microsoft even recommends setting this global `ServicePointManager.DefaultConnectionLimit` setting to a higher value: https://docs.microsoft.com/en-us/azure/storage/common/storage-performance-checklist#subheading9

However, if for some reason adjusting this setting is still required, my suggestion is to only adjust the setting for the specific `ServicePoint` objects used, for example:

[BlobStorageDataBus.cs](https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/blob/master/src/DataBus/BlobStorageDataBus.cs), method Start():
```
ServicePointManager.FindServicePoint(container.StorageUri.PrimaryUri).ConnectionLimit = settings.NumberOfIOThreads;
ServicePointManager.FindServicePoint(container.StorageUri.SecondaryUri).ConnectionLimit = settings.NumberOfIOThreads;
```

My proposal would be to remove setting the connection limit on the ServicePointManager completely.

**Comment by SeanFeldman** [comment]
Hi @marcelvwe, we have prioritized your issue near the top of our list and will be working on it as soon as we can.

**Comment by marcelvwe** [comment]
Thank you Sean. In the meantime we applied a workaround by resetting the value of the DefaultConnectionLimit to it's original value, immediately after the ServiceBus has been started.

**Comment by SeanFeldman** [comment]
@marcelvwe the fix has been released: https://discuss.particular.net/t/nservicebus-databus-azureblobstorage-3-0-1-2-1-1-1-1-2-patch-releases-available/1528. Thank you for your contribution and please update to the latest.

**Comment by marcelvwe** [comment]
Thank you Sean, we’ll update to this release.
